version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: elasticsearch-1
    environment:
      - node.name=elasticsearch-1
      - cluster.name=es-docker-cluster
#      - cluster.initial_master_nodes=elasticsearch-1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


volumes:
  elastic_data:
    driver: local